# Generated by Django 4.2.7 on 2023-12-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meseros',
            name='pais',
            field=models.CharField(default='', max_length=27),
        ),
    ]
